java.lang.NullPointerException
	at edu.brown.cs32.MFTG.tournament.Client.handleRequest(Client.java:134)
	at edu.brown.cs32.MFTG.tournament.RequestCallable.call(RequestCallable.java:24)
	at edu.brown.cs32.MFTG.tournament.RequestCallable.call(RequestCallable.java:1)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
java.lang.NullPointerException
	at edu.brown.cs32.MFTG.tournament.Client.handleRequest(Client.java:134)
	at edu.brown.cs32.MFTG.tournament.AIClient.run(AIClient.java:110)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
An error has occured. AI will now exit
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
	at java.io.BufferedWriter.flush(BufferedWriter.java:253)
	at edu.brown.cs32.MFTG.tournament.Client.write(Client.java:107)
	at edu.brown.cs32.MFTG.tournament.Client.sayGoodbye(Client.java:91)
	at edu.brown.cs32.MFTG.tournament.HumanClient.returnToWelcomeScreen(HumanClient.java:127)
	at edu.brown.cs32.MFTG.tournament.RequestCallable.call(RequestCallable.java:31)
	at edu.brown.cs32.MFTG.tournament.RequestCallable.call(RequestCallable.java:1)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
An error has occured. AI will now exit
